### ISSUE TITLE
stop_sync does not work as expected

### ISSUE THREAD

**Issue by gutleib** [shayonj/pg_easy_replicate#24]
(sorry, pressed enter to fast)

```
$ pg_easy_replicate stop_sync --group-name=dedic-migrate
/var/lib/gems/3.0.0/gems/pg_easy_replicate-0.1.4/lib/pg_easy_replicate/orchestrate.rb:172:in `stop_sync': wrong number of arguments (given 1, expected 0; required keywords: target_conn_string, source_conn_string, group_name) (ArgumentError)
        from /var/lib/gems/3.0.0/gems/pg_easy_replicate-0.1.4/lib/pg_easy_replicate/cli.rb:84:in `stop_sync'
        from /var/lib/gems/3.0.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/3.0.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/lib/gems/3.0.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /var/lib/gems/3.0.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /var/lib/gems/3.0.0/gems/pg_easy_replicate-0.1.4/bin/pg_easy_replicate:6:in `<top (required)>'
        from /usr/local/bin/pg_easy_replicate:25:in `load'
        from /usr/local/bin/pg_easy_replicate:25:in `<main>'
```
and, of course,
```
$ pg_easy_replicate stop_sync
No value provided for required options '--group-name'
```

**Comment by shayonj** [comment]
Thanks! Fixed in 0.1.5 🙌🏾
